### ISSUE TITLE
trouble in running dataset_cheaker.py

### ISSUE THREAD

**Issue by FelixZhang7** [peteryuX/arcface-tf2#11]
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_parse_tfrecord_98}} Feature: image/encoded (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]] [Op:IteratorGetNextSync]

**Comment by peteryuX** [comment]
Hi @FelixZhang7 ~ You already downloaded MS-Celeb-1M datasets, then extract and convert them to tfrecord as traning data right?

**Comment by FelixZhang7** [comment]
yes,i have convert mxrecord to tfrecord

**Comment by peteryuX** [comment]
That's weird. Do you mind provide me the tf.record you produced.

**Comment by FelixZhang7** [comment]
i have solved this problem but i got a new one

> python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 144, in finalize
    raise ValueError('Empty training data.')
ValueError: Empty training data.

**Comment by peteryuX** [comment]
Had you set your datase path in the config.file?

**Comment by FelixZhang7** [comment]
After cheaking the  data,i think i got worong dataset,but the ms1m112*112 in face.evoLVe.PyTorch is not available,could you provide baidu drive or google drive?

**Comment by peteryuX** [comment]
Check this tempral [backup](https://drive.google.com/drive/folders/1LmrvtaFsuXXmcWzr9U722HuZFt0NOq3W?usp=sharing).

**Comment by FelixZhang7** [comment]
I solved the dataset problem,but...
`"/home/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py",` line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 870, in _run_internal_graph
    assert str(id(x)) in tensor_dict, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("ArcHead/Identity:0", shape=(None, 85742), dtype=float32)`

**Comment by peteryuX** [comment]
So the dataset_checker.py is running well right now? Where the last error massage come from? May you please provide me more information about this? Thanks :)

**Comment by FelixZhang7** [comment]
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    app.run(main)
  File "/home/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 78, in main
    logist = model(inputs, training=True)
  File "/home/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 870, in _run_internal_graph
    assert str(id(x)) in tensor_dict, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("ArcHead/Identity:0", shape=(None, 85742), dtype=float32)

**Comment by peteryuX** [comment]
Hi @FelixZhang7~ I don't know why the problem present... I training with both binary and online image version tf.record dataset well. But the error message you provided is similar to https://github.com/peteryuX/arcface-tf2/issues/7. Hope this information can help you. Is there any possible still have any difference between with the steps in my repo?

**Comment by FelixZhang7** [comment]
I solved that according to the link, Thank you so much! Sorry to disturb you for a long time

**Comment by CptK1ng** [comment]
> i have solved this problem but i got a new one
> 
> > python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 144, in finalize
> > raise ValueError('Empty training data.')
> > ValueError: Empty training data.

Could you please give additional information how you solved your problem?

Thanks
