### ISSUE TITLE
SIze of model

### ISSUE THREAD

**Issue by seunboy1** [peteryuX/arcface-tf2#13]
Thank you for this project. 
I would like to know if there is a way to reduce the size of the model using MobileNetV2 as backbone architecture.

**Comment by peteryuX** [comment]
Hi @seunboy1 ~ The input argment `alpha` in the `tf.keras.applications.MobileNetV2()` is the thing you want~ (detail in [here](
https://github.com/tensorflow/tensorflow/blob/5041f45fdb0f3ff10645080a06d7ab7b13fa0a95/tensorflow/python/keras/applications/mobilenet_v2.py#L98)).

**Comment by seunboy1** [comment]
Ok, thank you

**Comment by seunboy1** [comment]
Hi how do i create a pb file from the checkpoint

**Comment by peteryuX** [comment]
Call `tf.keras.models.save_model(model, "filepath_you_want") in test.py.`
