### ISSUE TITLE
Question regarding evaluation metric

### ISSUE THREAD

**Issue by YotamNitzan** [peteryuX/arcface-tf2#14]
Hi, thanks for sharing the project !

I am wondering about the metric used for distnace of embeddings.
From what I understand, you use L2 in the following code:

https://github.com/peteryuX/arcface-tf2/blob/66d0afb124c74b6c1e0b79a464325472ede6fb45/modules/evaluations.py#L72-L73

While, the offical code seems to use cosine similarity in all evaluations.
For example:

https://github.com/deepinsight/insightface/blob/1af6eeffdc1fe1d81c308fafe37f28883c5cf27f/Evaluation/IJB/IJB_1N.py#L117

Am I missing something ? Is this intentional ? 
I'd appreciate your clarification.

**Comment by peteryuX** [comment]
Hi @YotamNitzan , nice to here from you~ About the code you mentioned is corresponding to 
https://github.com/deepinsight/insightface/blob/1af6eeffdc1fe1d81c308fafe37f28883c5cf27f/src/eval/verification.py#L76 , which I actually modified from from https://github.com/ZhaoJ9014/face.evoLVe.PyTorch.

Is that clarify your confusion?

**Comment by YotamNitzan** [comment]
Thanks for your immediate response.

I read some more and from what I understand, its completly a matter of choice which metric to use. Probably whatever causes better results.
As you pointed out insightface seems to use both, depending on the script.
Also in: https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/d5e31893f7e30c0f82262e701463fd83d9725381/util/verification.py#L53-L54
It is possible to switch the metric used from euclidean to cosine.

Maybe, it would be nice to expose it as an argument in the test script ?

**Comment by peteryuX** [comment]
Hi @YotamNitzan , thanks for your advices and attentions. From my previous opinion, I think the rank is same in both cosine similarity and l2 distance as the vectors be normalized
(https://stats.stackexchange.com/questions/146221/is-cosine-similarity-identical-to-l2-normalized-euclidean-distance), so I didn't write both metrics in script. However, I will add cosine metrics as a argument after few day (I am not at home), if that distance value could let somebody get more understanding about the distance meaning.

**Comment by YotamNitzan** [comment]
Oh, you're right... the reference clarifies it. They are equivalent if the vectors are normalized.
Thanks for helping out.

Closing the issue, keep on the good work !
