### ISSUE TITLE
Test script

### ISSUE THREAD

**Issue by aideveloper97** [peteryuX/arcface-tf2#16]
Hi @peteryuX, thank you for your amazing work. i wont to know the recommended threshold value for validating if 2 images are similar.

**Comment by peteryuX** [comment]
Hi @aideveloper97 , I think you can try 1.35 firtly as the threshold if your task is focus on face recoginition~

**Comment by aideveloper97** [comment]
Is this after using L2 distance on the 2 saved numpy arrays or is it another distance metrics that i am to use.

**Comment by peteryuX** [comment]
The l2 distance between two  normalized embed vectors!

**Comment by aideveloper97** [comment]
Okay thank you
