### ISSUE TITLE
get nan result for a whole batch 

### ISSUE THREAD

**Issue by gitlabspy** [peteryuX/arcface-tf2#29]
Hi, 
Thanks for sharing this amazing work! I downloaded your model and loaded the weights, resnet-50 ccrop=true, and I test it with a bunch of images. Some batches work fine, no nan, but some batches are all nan results. What might cause this?

**Comment by sfxnminimah** [comment]
Hi,
Pls did you solve this issue? Getting the same nan results for some batches too
