### ISSUE TITLE
[*] Cannot find ckpt from None

### ISSUE THREAD

**Issue by dvatsal** [peteryuX/arcface-tf2#3]
Hi 

I am running 

`python test.py --cfg_path="./configs/arc_res50.yaml"`

What can be the issue?

**Comment by peteryuX** [comment]
Have you download or prepared  model checkpoints for restoring?

**Comment by dvatsal** [comment]
I haven't downloaded model.When I tried to run it first time - it was dowloading something and at the end it became still/unresponsive

**Comment by peteryuX** [comment]
I guess the first-time downloading things are the keras resent50 pretrain weights, but not the checkpoints I meaning. Please download model I prepared in repo to skip the issue above.

**Comment by dvatsal** [comment]
I will try and let you know.Thanks for your quick response.

**Comment by galuhputraa** [comment]
im still doesnt understand can u explain briefly to me? im already download the model and put in in the folder checkpoints , and getting this error?
