### ISSUE TITLE
Issues with perform_val

### ISSUE THREAD

**Issue by krumnack** [peteryuX/arcface-tf2#40]
The function `perform_val` (from `modules.evaluations`) seems to have two issues:

- it evaluates the test data without converting from BGR to RGB: in the test data archives (`lfw_align_112.zip`, ...) the images are provided in BGR Format, and that is used in evaluation. But the training procedure uses the RGB format (as obtained from `tf.image.decode_jpeg`). Evaluating on RGB images instead of BGR can slightly (but consistently) improve the results, e.g. with the pretrained ResNet50 from 99.35% to 99,42% for LFW and from 90.36% to 92.56% for CFP-FP.
- when providing the parameters `is_ccrop=True, is_flip=False`, center cropping is performed twice, drastically reducing the performance in that case.

**Comment by peteryuX** [comment]
Hey @krumnack,
Thank you for the heads-up!
I had already fix this two problem in the latest commit 6447e9d04451aba1ef262f43c77ae50cdfaf19f8.
Enjoy it! Have a good day :) ~

**Comment by krumnack** [comment]
That was quick - thanx!
