### ISSUE TITLE
Colab notebook does not work(for downloading arc_res50.zip file)

### ISSUE THREAD

**Issue by jinholeetopology** [peteryuX/arcface-tf2#45]
Could you let me know how to get the zip file arc_res50.zip?
I attached the warning messege.
From this error, I cannot make checkpoints folder.

Downloading 1HasWQb86s4xSYy36YbmhRELg9LBmvhvt into ./arc_res50.zip... Done.
Unzipping.../usr/local/lib/python3.7/dist-packages/google_drive_downloader/google_drive_downloader.py:78: UserWarning: Ignoring `unzip` since "1HasWQb86s4xSYy36YbmhRELg9LBmvhvt" does not look like a valid zip file
  warnings.warn('Ignoring `unzip` since "{}" does not look like a valid zip file'.format(file_id))
mv: cannot stat 'arc_res50': No such file or directory

**Comment by jinholeetopology** [comment]
I found the direct download link.

**Comment by Snehendu99** [comment]
> I found the direct download link.

can you give the direct link please ?
