### ISSUE TITLE
训练epoch问题

### ISSUE THREAD

**Issue by linwaydong** [peteryuX/arcface-tf2#5]
请问下大神，你在MS-Celeb-1M数据集上训练5个epoch就能达到Verification results中的效果吗？

**Comment by peteryuX** [comment]
小弟不是大神orz，不過verification results確實是訓練5個epoch後得到的。

**Comment by linwaydong** [comment]
> 小弟不是大神orz，不過verification results確實是訓練5個epoch後得到的。

训练log能给我看看吗？我用arcface loss时候loss降得很慢，正常吗？

**Comment by peteryuX** [comment]
不好意思，log沒留著，不過你可以待到training結束後，跑test.py測測看性能，前幾天close的issue也剛好提及你相關的情況歐!
